### ISSUE TITLE
Looking for new owner for domains

### ISSUE THREAD

**Issue by rvagg** [openopensource/openopensource.github.io#22]
I have openopensource.com and openopensource.org but I'd like to hand them over to someone else if anyone cares enough to take some responsibility. If so, please make your case so I can find a new owner.

**Comment by rvagg** [comment]
the domains expire in 5 days and I'm letting them drop, FYI

after that I might archive this repo

**Comment by ariesclark** [comment]
The domain is now some spam/phishing content.
